// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rivswwdjhwgnnqqlysjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpdnN3d2RqaHdnbm5xcWx5c2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NjE2NTUsImV4cCI6MjA3MjAzNzY1NX0.TrPdyxPz8Ezb3FJQeKSZO_A8seP2sW86am352f3bLVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});