// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adqnhvsfoixiupxuvohw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkcW5odnNmb2l4aXVweHV2b2h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTU2MTMsImV4cCI6MjA2NDUzMTYxM30.rOTDEY3MccLISeMCPQJ9N3rHGmNDO2GjPiUc4yJtU3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});